### PR TITLE
Consistent `FeaturePlot` axis limits

### PR DESCRIPTION
**Pull request by mfansler**
This partially addresses what is documented in Issue #1260. In particular, it fixes a bug in `FeaturePlot` that currently causes the shared y-axis limits to be discarded during subsequent changes to the axis.

Ideally, a proper fix would rework the code to avoid overwriting the axis scaling in the first place. Instead, this PR minimally patches the current code to make sure the `limits` argument of `scale_y_continuous` is consistently set throughout.

### CODE REVIEW

**Comment by mfansler** [comment]
Looking at this again, I realized that the issue I cited does not actually document the bug this fixes. Below is an example, where splitting by samples (`condition` in the code below) results in subsets of cells that occupy different parts of the tSNE plot. The current `FeaturePlot` code fails to preserve the y-axis across the plots, making it less than ideal for visual comparison. This PR would instead yield consistent axes applied throughout.

---

### Example Code

``` lang: r
library(magrittr)
library(Seurat)

## data from Dobie et al., 2019
seu.chronic %>%
  subset(subset=(enrichment == "HSC")) %>%
  FeaturePlot(features=c("nGene", "nUMI", "percent.mito", "effectiveGenes"), 
              split.by="condition", label=TRUE, coord.fixed=TRUE,
              cols=viridis::plasma(20))
```

### Result
image

**Comment by mojaveazure** [comment]
Thanks for catching this, Mervin!

**Comment by sameetmehta** [comment]
This problem is not fully solved.  I used another dimensionality reduction, but the plot is with x, and y limits c(-1, 1).  If I trying to do `p + xlim(-0.05, 0.05)`, and I have used `split.by` in the `FeaturePlot`, only the last plot is plotted at correct limits, not the others.

**Comment by mfansler** [comment]
> This problem is not fully solved. I used another dimensionality reduction, but the plot is with x, and y limits c(-1, 1). If I trying to do `p + xlim(-0.05, 0.05)`, and I have used `split.by` in the `FeaturePlot`, only the last plot is plotted at correct limits, not the others.

Hi @sameetmehta 

This patch was not intended to provide post-processing adjustments such as that shown by your example. AFAIK, currently there is not an interface in the API to manually specify axis limits. In order to get your example to work effectively as a post-processing adjustment, one would need to iterate through all the subplots in the ggplot object and add the `xlim(...)` directive to each.

If this is a feature you expect to frequently require and suspect others might want it, then it may be worth adding it to the API directly (i.e., avoid post-processing). In that case, consider creating a new issue for such a feature request and see if there is any feedback for how best to add it. At a glance, I think one could add `xlims` and `ylims` arguments to the `FeaturePlot` function, then check to see if those are non-NULL ([probably here in the code](https://github.com/satijalab/seurat/blob/0bbb2797e0a717aa7dc09d95781be53987f1907f/R/visualization.R#L1107)), using those values instead of the extremes of the data.

**Pull request merged**
