### PR TITLE
Improve setting of cell names

### PR DESCRIPTION
**Pull request by lazappi**
With more people combining datasets for analysis with `RunMultiCCA` fixing duplicate cell names is becoming more of a problem as seen in #270, #290, #400, #505. To address this I have made the following changes:

* Add a new `RenameCells` function that renames cells either by adding a prefix or replacing with a new vector of names
* Modified `MergeSeurat` to use the new `RenameCells` function (to avoid duplication)
* Add a new `add.cell.ids` parameter to `RunMultiCCA` which applies `RenameCells` to each object in `object.list`
* Add new documentation and tests

### CODE REVIEW

**Comment by lazappi** [comment]
Merged develop to hopefully get Travis working after #511.

**Comment by andrewwbutler** [comment]
Thanks Luke! Very helpful function and should reduce confusion when analyzing multiple datasets.

**Comment by nbahlis** [comment]
Hello, 
when using RenameCells I get the error "invalid dimnames given for "dgCMatrix" object "
Does RenameCells work with sparse matrices?

thanks

**Comment by lazappi** [comment]
@nbahlis I think it might be better to discuss this as an issue rather than on this pull request so I have opened #523

**Pull request merged**
