### PR TITLE
Fix ssl problem in bioc_install command

### PR DESCRIPTION
**Pull request by roi-meir**
# Problem 
Currently, the tests fail at the first `bioc_install` command because of SSL error 

For example:
```
package 'BiocManager' successfully unpacked and MD5 sums checked
The downloaded binary packages are in
	C:\Users\appveyor\AppData\Local\Temp\1\RtmpSQSWPh\downloaded_packages
Error: Bioconductor version cannot be validated; no internet connection?  See
  #troubleshooting section in vignette
In addition: Warning messages:
1: In file(con, "r") :
  URL 'https://bioconductor.org/config.yaml': status was 'SSL connect error'
2: In file(con, "r") :
  URL 'https://bioconductor.org/config.yaml': status was 'SSL connect error'
Execution halted
Command exited with code 1
7z a failure.zip *.Rcheck\*
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
```

# Fix 
Set R_LIBCURL_SSL_REVOKE_BEST_EFFORT to TRUE (see https://stat.ethz.ch/R-manual/R-devel/library/utils/html/download.file.html for details)

### CODE REVIEW

**Comment by roi-meir** [comment]
It turns out that the variable `CURL_SSL_BACKEND='openssl'` is also needed

**Comment by rharao** [comment]
Thanks for this. Because of the Appveyor error, this PR is the first to pass CI checks in more than a year. I hope the maintainers will merge this or pursue something like #7751.

**Comment by rharao** [comment]
@roi-meir #9538 would cut out Appveyor altogether

**Comment by dcollins15** [comment]
@roi-meir I can't tell you how much I appreciate the effort you put into getting these checks back up and running 🙏 

As @rharao pointed out, we _are_ planning to move away from AppVeyor in favor of GitHub actions and https://github.com/satijalab/seurat/pull/9538 drops the corresponding config files accordingly. On second thought, there's probably utility in having both sets of checks running concurrently for a little while to make sure nothing is sneaking through the new set that shouldn't be (in general the new checks should be stricter than the old but still). 

Unless you've got any objections, I'll revert [d669d9d](https://github.com/satijalab/seurat/pull/9538/commits/d669d9dd97986e6ca217608d3458c9ab727d8213) and then squash-merge `roi-meir:bugfix/fix_ssl_error_in_travis` into `satijalab:ci_revamp` so that your fix is incorporated when https://github.com/satijalab/seurat/pull/9538 is merged to `develop`.

**Comment by roi-meir** [comment]
Sound good for me. 
Thank you for developing this amazing tool!

**Comment by dcollins15** [comment]
Closing in favor of:
- https://github.com/satijalab/seurat/pull/9538

**Pull request closed without merging**
