### PR TITLE
just a tiny suggestion

### PR DESCRIPTION
**Pull request by opitzl**
Dear Seurat-Dev-Team,
it would be nice if the Read10X function 
would support an optional prefix in the CellRanger output data or to read 10X data from GEO without renaming.

### CODE REVIEW

**Comment by samuel-marsh** [comment]
Agree this would be great if implemented.

In meantime as fyi I have written functions to handle such situations (GEO files etc) in my package scCustomize.  `Read10X_GEO` can read in one or more files from same directory with prefixes and if you are reading all files doesn’t require you to specify prefix or files to share prefix (will return list with entries named by prefix).
https://samuel-marsh.github.io/scCustomize/articles/Read_and_Write_Functions.html

Best,
Sam

**Comment by samuel-marsh** [comment]
Will also add if you want Seurat native solution you can simply use `ReadMtx` function.

Best,
Sam

**Comment by samuel-marsh** [comment]
Also actually just remembered `ReadMtx` was solution added when I sent similar PR while back #4101 .  So think that will likely remain supported solution to file prefix/non-standard names.

Best,
Sam

**Comment by saketkc** [comment]
Hi @opitzl and @samuel-marsh, thanks for the suggestion and discussion. We think `ReadMtx` is a versatile approach to handle these cases. Thanks for your PR @opitzl - we really appreciate it, but also want to keep the technology specific methods (such as 10X) to do exactly one task. Please use `ReadMtx` for other use cases.

**Comment by samuel-marsh** [comment]
Thought as much based on our previous conversations!  Thanks again @saketkc!

**Pull request closed without merging**
