### PR TITLE
moved progress output from STDOUT to STDERR (knitr compatibility)

### LINKED ISSUE #45: progress output clutters knitr output
When running Seurat through `knitr` in an `Rmd` file, Seurat's progress output clutters the resulting output document.

This is caused by Seurat printing its diagnostic output to `STDOUT` instead of `STDERR` as common.

Also see [this answer of the `knitr` dev on the subject](http://stackoverflow.com/a/20024043/2451238).

### PR DESCRIPTION
**Pull request by mschilli87**
fixes #45

### CODE REVIEW

**Comment by mschilli87** [comment]
The [build error](https://travis-ci.org/satijalab/seurat/builds/202656813) seem to be [unrelated to my changes](https://travis-ci.org/satijalab/seurat/builds/202656813#L187).

**Comment by mschilli87** [comment]
closing & re-opening to trigger re-build

**Comment by mschilli87** [comment]
Whatever is causing it, [the build error persists](https://travis-ci.org/satijalab/seurat/builds/202688097).

This looks like an idependent issue, either with your Travis configuration or upstream.

I'm not sure how to further debug this issue.

Please consider testing my pull request independently (as suggested [above](https://github.com/satijalab/seurat/pull/46#issuecomment-280680653)).

**Comment by andrewwbutler** [comment]
Sorry for the slow follow up. Something upstream was breaking a lot of R package builds on Travis but it seems to have been resolved. Seems like a good solution to making knitting these kinds of documents less messy.

**Pull request merged**
