### PR TITLE
Adding ReadAlevin function [WIP]

### PR DESCRIPTION
**Pull request by k3yavi**
Hi Seurat team,
First of all thanks for the awesome tool, it has helped us and our user base a lot in analyzing the scRNA-seq data.

We have recently developed a dscRNA-seq quantification pipeline with name `Alevin` (preprint [here](https://www.biorxiv.org/content/early/2018/10/24/335000)), and we frequently encounter feature requests from our user base regarding the preprocessing of the reads for subsampling/batch correction like https://github.com/COMBINE-lab/salmon/issues/305.  We generally recommend users to go through [this](https://combine-lab.github.io/alevin-tutorial/2018/alevin-seurat/) tutorial to parse the Alevin output and perform bias correction through Seurat package downstream of Alevin. In lieu of that to simplify the clustering pipeline by one more step we'd love to make the following pull request to parse the Alevin output and would really appreciate, if possible, to optimize the committed parsing function and merge to master in your next release.

Alevin dumps both `csv` and a more efficient binary format. We are working on writing a parser for the binary format and would update this pull request soon. As a noob in `R` I'd appreciate if you see something horribly wrong in the committed parsing code and would appreciate your feedback.

### CODE REVIEW

**Comment by mojaveazure** [comment]
Hi Avi,

I know this is a work in progress, but could you make sure you're building off of the `release/3.0` branch? We're revamping the Seurat object system and how Seurat is organized, so we'd like all incoming pull requests to target this new scheme.

**Comment by k3yavi** [comment]
Sounds good @mojaveazure , thanks for the heads up !

**Comment by k3yavi** [comment]
Hi @mojaveazure , I have the relevant changes ready in the forked seurat repo in an updated `release/3.0` branch. Should I make a new pull request or push the changes into develop for which this pull request was made ?

**Comment by mojaveazure** [comment]
Hi Avi, whichever's easiest for you. A new PR might be cleaner, but it's up to you.

**Comment by k3yavi** [comment]
Thanks @mojaveazure , I'll make a new one then and close this one.

**Pull request closed without merging**
