### PR TITLE
custom group colors DoHeatmap/SingleRasterMap

### PR DESCRIPTION
**Pull request by dpschreiner**
refer to issue  #1048

this works for me. if you customize your heatmap colors (expression) and use space between groups, then you have to add another argument, i.e.

scale_fill_gradientn(colors = c("blue", "white", "red"), **na.value = 'white'**)

### CODE REVIEW

**Comment by dpschreiner** [comment]
oh, it looks like it failed due to the example. that was foolish - i didn't know it would try to execute it.  was trying to be helpful!

**Comment by mojaveazure** [comment]
Hi David,

Thanks for the PR! I've made some changes, generally moving the logic into `DoHeatmap` rather than spread across multiple functions. I've also added the ability for `DoHeatmap` to fill in colors if too few were specified in `group.colors`. Let me know if you have any questions/comments/concerns about these changes and once resolved, we'll get it merged in.

**Comment by Dragonmasterx87** [comment]
Hi @mojaveazure do you have any idea how to change the color of the label bar on top of the heatmap? Please if you could suggest a line of code which could allow for the implementation of something like HTML codes, so that we have multiple color options for the label.

Cheers!
Fahd

**Comment by Dragonmasterx87** [comment]
My apologies I just saw [this](https://rdrr.io/cran/Seurat/man/DoHeatmap.html) 

🤦‍♂

**Pull request merged**
