### PR TITLE
Typo combined

### PR DESCRIPTION
**Pull request by samuel-marsh**
Hi Seurat Team,

Given updates to dev branch and CI checks I thought it might be helpful to condense a number of typo fixes into single PR that is on current develop branch.

Thanks to authors of original PRs @josura @agdenadel @tnqvuong @kew24 @nrockweiler @eroell @mauriziopaul @AlbertoFabbri93.

Best,
Sam

### CODE REVIEW

**Comment by rharao** [comment]
I snuck a typo fix into my PR at https://github.com/satijalab/seurat/pull/9493/commits/05aedba7f85c18b1c8c7afcf3a924b8a0f7b4bbc ; you can cherry pick it if you want

**Review by dcollins15 — APPROVED** [review]
I cannot tell you how much I appreciate this @samuel-marsh! 🙌 

LG(reat)TM 🚀

**Comment by rharao** [comment]
With this merge, the open PRs are down to 25-- few enough to fit on one page :smile: great momentum you have going @dcollins15

**Comment by samuel-marsh** [comment]
@dcollins15 always happy to help! :)

**Pull request merged**
