### PR TITLE
Support for multiple 10x data directories

### PR DESCRIPTION
**Pull request by ryanrichholt**
Read10X now accepts a vector of data directories. Optionally, this can be a named vector and the names will be appended to the cell barcodes. Single data dir functionality is preserved.

### CODE REVIEW

**Comment by andrewwbutler** [comment]
Whoops, still figuring out Github's new code review system. I would also ask that you update the function docs to reflect the new functionality. Thanks!

**Comment by ryanrichholt** [comment]
Okay, now it should only prefix cell barcodes if the vector is named, and the docs are updated. I accidentally committed twice (new to this), but I think the changes should be reflected now.

**Comment by andrewwbutler** [comment]
Merged in the changes. Thanks again Ryan

**Review by invisiblepancake — COMMENTED** [review]
The changes in this commit enhance the Read10X function by allowing it to support named vectors for loading multiple data directories. This update is beneficial because it improves data organization and clarity by prefixing cell barcode names with the directory name when a named vector is provided. This makes it easier to manage and distinguish data from different sources, which is crucial for projects dealing with multiple datasets. Overall, these changes enhance the flexibility and usability of the Read10X function.

**Pull request merged**
