### PR TITLE
Xenium vignette

### PR DESCRIPTION
**Pull request by jsicherman**
Adding a vignette for working with Xenium data. The data currently used in this vignette is pre-release data. Full release is scheduled ~next week.

### CODE REVIEW

**Comment by jsicherman** [comment]
Hi @mojaveazure and et al. Hoping to get this Xenium vignette loaded up into Seurat now that we have our public data release ready. Let me know if any changes are necessary to get it into a format that you all prefer!

**Comment by AustinHartman** [comment]
Hi @jsicherman, thanks for the PR. I'm going to update the existing imaging-based spatial transcriptomics vignette ([https://satijalab.org/seurat/articles/spatial_vignette_2.html](https://satijalab.org/seurat/articles/spatial_vignette_2.html)) in the next day to include Xenium data and I can send you a site preview for your ok before pushing to the public site. Does that work?

**Comment by jsicherman** [comment]
Sounds good, thanks @AustinHartman!

**Comment by AustinHartman** [comment]
Closing since this is now in the develop branch with some small changes and live on the website

**Pull request closed without merging**
