### PR TITLE
[RDY] Use random seed to for Leiden algorithm

### LINKED ISSUE #1683: Leiden algorithm does not use random seed
Hi,

running 

`data <- FindClusters(data,algorithm=4,random.seed = 0)`

twice in a row returns different clustering results. 

The `find_partition` method from the `leidenalg` package has a `seed` argument. Is there a specific reason the `random.seed` argument is not passed through?

### PR DESCRIPTION
**Pull request by mschilli87**
fixes #1683

Untested, solution proposed by @ccasar.

### CODE REVIEW

**Comment by mschilli87** [comment]
force-pushed rebase on force-pushed `develop` branch

**Comment by mschilli87** [comment]
@ccasar: Could you try the updated branch again?

**Comment by ccasar** [comment]
Yes, this seems to work now. Two clustering runs with and without use of `random.seed` for `FindClusters` produce the same clustering.

**Comment by mschilli87** [comment]
squashed and force-pushed for clean merge

**Comment by andrewwbutler** [comment]
Thanks @mschilli87 and @ccasar!

**Pull request merged**
