### PR TITLE
Bug-fix of FindClusters Leiden algorithm

### PR DESCRIPTION
**Pull request by chlee-tabin**
This is a short fix to make a consistent behavior of `FindCluster` function with algorithm = 4. See https://github.com/satijalab/seurat/issues/2438 for the issue.

# Note

Thanks for your interest in contributing! Please make your PR to the `develop` branch. You can check out our [wiki](https://github.com/satijalab/seurat/wiki) for the current developers guide.

### CODE REVIEW

**Comment by andrewwbutler** [comment]
Thanks for reporting! I made a few refactoring changes as I was trying to understand the issue. 

I also noticed that when converting to the igraph object from something that inherits from `c('dgCMatrix', 'matrix', "Matrix")`--- note that this includes `Graphs` ---, the edge weight information was lost so I added `weighted = TRUE` to this. However, I'm still not getting the same results with `method = 'matrix'` as with `method = 'igraph'`. 
```R
> library(SeuratData)
> data("pbmc3k.final")
> 
> pbmc3k_igraph <- FindClusters(pbmc3k.final, algorithm = 4, method = "igraph")
> table(Idents(pbmc3k_igraph))
  1   2   3   4   5   6   7   8 
682 493 473 344 284 182 147  33 
> pbmc3k_matrix <- FindClusters(pbmc3k.final, algorithm = 4, method = "matrix")
> table(Idents(pbmc3k_matrix))
  1   2   3   4   5   6   7   8   9  10  11 
574 486 344 272 255 225 162 145 129  32  14 
```
Do you have any idea why this might be @TomKellyGenetics?

**Comment by TomKellyGenetics** [comment]
I'm not sure that changes in bb3c8a6be11f2 is doing anything. When we added the igraph method https://github.com/satijalab/seurat/pull/2169 this was discussed. The Seurat "Graph" Class is a sparse matrix so running `is.Matrix` should return TRUE.

I'm not sure about the difference raised by @andrewwbutler though. Did you see this in the previous version? I'm not sure the refactored code is doing the same thing (sorry I'm finding it difficult to mentally parse). If there's still an issue, I can check if the package being called (https://github.com/TomKellyGenetics/leiden) has a similar issue with the same input graph.

Please note that the "matrix" method is recommended as it's faster for smaller datasets. The "igraph" method is only needed for large graphs (of many cells).

**Comment by TomKellyGenetics** [comment]
You can check that the `leiden` implementations return the same result here. Bear in mind that you need to set the "seed" as they use different random initial states.

```{r}
mat <- round(matrix(runif(100), 10, 10), 0)
mat
part_mat <- leiden::leiden(mat)
graph <- igraph::graph_from_adjacency_matrix(mat)
graph
part_mat <- leiden::leiden(mat, seed = 9000)
part_mat
part_graph <- leiden::leiden(graph, seed = 9000)
part_graph
table(part_mat, part_graph)
```

Screen Shot 2020-01-15 at 9 48 43

Here you can see the same result for Seurat. Perhaps the issue is passing the weighted graph?

```{r}
rownames(mat) <- colnames(mat) <-1:10
obj <- Seurat::CreateSeuratObject(mat)
obj <- Seurat::FindVariableFeatures(obj)
obj <- Seurat::ScaleData(obj)
obj <- Seurat::RunPCA(obj, dim = 1:3)
obj <- Seurat::FindNeighbors(obj, dim = 1:3)
obj <-Seurat::FindClusters(obj, algorithm = "Leiden")
part_mat <- obj@active.ident
obj <-Seurat::FindClusters(obj, algorithm = "Leiden", method = "igraph")
part_graph <- obj@active.ident
table(part_mat, part_graph)
```

Screen Shot 2020-01-15 at 9 54 11

**Comment by chlee-tabin** [comment]
@TomKellyGenetics "With Seurat 3.1.1, I have no issue getting the same results."

Just to make sure I am on the same page, the issue came up at 3.1.2, NOT at 3.1.1. Specifically, I was comparing the code changes between 3.1.1 and 3.1.2 and found that at least the logic changed .

**Comment by chlee-tabin** [comment]
> I'm not sure that changes in [bb3c8a6](https://github.com/satijalab/seurat/commit/bb3c8a6be11f2b7cd0b866b2106b4c461097ef1d) is doing anything. When we added the igraph method #2169 this was discussed. The Seurat "Graph" Class is a sparse matrix so running `is.Matrix` should return TRUE.

I think (I may be wrong) without that line, `graph_from_adjacency_matrix` is called to the object, generating different behavior than from 3.1.1 (as discussed as a reproducible example in https://github.com/satijalab/seurat/issues/2438 ). The refactor https://github.com/satijalab/seurat/pull/2440/commits/721a97011ed97ef22832977400d5b447549820ac is most likely not going to do this diversion.

**Comment by TomKellyGenetics** [comment]
I'm not sure about the new version. The current version installed on my laptop returns the same results for both methods (as does the package being called). This means that the difference (if it can be reproduced) is a result of changes made since. You can see the reasons for #2169 in Issue #2168. Perhaps this may help to identify the problem.

Based on the results for the `leiden` package, I think the problem would be how arguments are passed from Seurat objects to it. As shown above, calling `graph_from_adjacency` on a matrix and running the `leiden` methods, gives the same results.

**Comment by chlee-tabin** [comment]
> I'm not sure about the new version. The current version installed on my laptop

Just to make sure I get this right, your current version is 3.1.1? If so, I expect no issue. If it is 3.1.2, and you still have no issue for the following:

```
library(tidyverse)
library(Seurat)
pbmc_small %>% FindNeighbors( dims = 1:10 ) %>% FindClusters( algorithm = 4 ) %>% DimPlot()
sessionInfo()
```

I would be surprised. As I said, I do not see any reason to point to the leiden algorithm per se to be the issue. Probably I should have made a more clearer title for the issuee. It is the FindClusters that packages the Leiden algorithm that got changed in logic from 3.1.1 (working well) to 3.1.2 (not working).

**Comment by chlee-tabin** [comment]
I hope I did not create a confusion of the issue title, but I am *not* talking about the `leiden` algorithm per se. As I understand, prior to 3.1.2 version, `FindClusters` function, when finding in a `Seurat` object a `Graph`, would just pass the object as a matrix to the `leiden` package. On 3.1.2 (and also the refactored version https://github.com/satijalab/seurat/pull/2440/commits/721a97011ed97ef22832977400d5b447549820ac ) will first pass the object to `graph_from_adjacency` to be passed to the leiden package and is creating issues.

**Comment by andrewwbutler** [comment]
Thanks for looking into this guys. Just to make sure that I'm understanding correctly, the `leiden` function can take either a dense matrix, a sparse matrix, or an igraph object? Did a bit more testing (leiden v0.3.1) using the pbmc3k SNN graph below:

``` r
suppressMessages(library(SeuratData))
library(leiden)

data("pbmc3k.final")
input <- pbmc3k.final[["RNA_snn"]]

# Test 1
sparse.input <- leiden(
  object = input, 
  seed = 42, 
  n_iterations = 10
)
head(table(sparse.input), 10)
#> sparse.input
#>  1  2  3  4  5  6  7  8  9 10 
#>  4  2  2  2  1  1  1  1  1  1

# Test 2
dense.input <- leiden(
  object = as.matrix(input), 
  seed = 42, 
  n_iterations = 10
)
head(table(dense.input), 10)
#> dense.input
#>   1   2   3   4   5   6   7   8   9  10 
#> 570 492 344 272 255 225 162 145 127  32

# Test 3
adj.graph <- leiden(
  object = igraph::graph_from_adjacency_matrix(input),
  seed = 42,
  n_iterations = 10
)
head(table(adj.graph), 10)
#> adj.graph
#>  1  2  3  4  5  6  7  8  9 10 
#>  4  2  2  2  1  1  1  1  1  1
all.equal(sparse.input, adj.graph)
#> [1] TRUE

# Test 4
adj.graph.weighted <- leiden(
  object = igraph::graph_from_adjacency_matrix(input, weighted = TRUE),
  seed = 42,
  n_iterations = 10
)
head(table(adj.graph.weighted), 10)
#> adj.graph.weighted
#>   1   2   3   4   5   6   7   8   9 
#> 568 485 473 344 275 182 147 131  33
all.equal(adj.graph.weighted, dense.input)
#> [1] "Mean relative difference: 0.3211488"
```

<sup>Created on 2020-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Currently (Seurat v3.1.2), by default we are in the scenario where `method = "matrix"` and the input is a `Graph` object. Following the if/else flow here https://github.com/satijalab/seurat/blob/7da0da958261cacaba601598272f7fc39004416b/R/clustering.R#L727-L738 

`input` gets coerces to an `igraph` object similar to test 3 above . Previously (Seurat v3.1.1), `input` would always get coerced to a dense matrix if `method = "matrix"` similar to test 1 above. https://github.com/satijalab/seurat/blob/fc4a4f5203227832477a576bfe01bc6efeb23f51/R/clustering.R#L708-L724

I believe this is the discrepancy that @chlee-tabin is trying to address. One solution is to always cast to dense matrices for `method = "matrix"` but if `leiden` supports sparse matrices as input, we should try to figure out why test 1 and test 2 give different results. 

Also for `method = "igraph"` is does seem that `leiden` supports both weighted and unweighted `igraph` inputs (tests 3 and 4). However, it's not clear to me why in Seurat, we shouldn't always be using `weighted  = TRUE` and why when we do that (test 4), the results aren't the same as if we had passed a matrix (test 2).

**Comment by TomKellyGenetics** [comment]
Thanks @andrewwbutler, at the moment `leiden` has a "method" for sparse matrices but it doesn't matter whether Suerat uses a sparse or dense matrix as `leiden` R package will coerce it to a dense matrix anyway. This is needed because `reticulate` can only pass a dense matrix or list to Python. This is the reason for the issue raised in #1645.

The `igraph` method passes an edgelist to Python instead. Testing coercing matrix to igraph gives the same results from `leiden`.  I'm not sure why the Seurat calls would give a different result. Perhaps it is an issue with how weighted Graphs are called? Now that weights are supported by `leiden` (as of v0.2.3), then I agree it should be the recommended behaviour for Seurat. I will check whether weighted graphs are passed from Seurat correctly.

**Comment by TomKellyGenetics** [comment]
I've found an issue with passing weights in `leiden` with igraph objects. https://github.com/TomKellyGenetics/leiden/commit/888e0b62fd1693de47f638b131a4194a1d6c236f

This is pushed to the development version. I'll send a PR to this branch to correct passing weights in Seurat.

**Comment by TomKellyGenetics** [comment]
@chlee-tabin Thanks for raising this issue. I've updated both `leiden` and your PR to ensure that calling `FindClusters` on a Seurat object returns the same results as calling it on an igraph object or matrix directly. I've attached the testing script. Please accept the PR to merge changes (https://github.com/chlee-tabin/seurat/pull/1/commits/53f0ea8341092536b09ce222d4e197039e038bb8) to the refactored version, this enables passing weighted igraph objects from `Seurat`.

@mojaveazure @andrewwbutler Can we hold off on merging this until I've uploaded the corrected version (0.3.2) of `leiden` to CRAN? I'd put a dependency on this version in the next release of `Suerat` as this is required to pass weights with igraph.

Please note that weights are supported by `leiden::leiden` and `Suerat::RunLeiden` but are not currently the default. Further changes will be needed to support weights in `FindClusters`.

[test_leiden.R.txt](https://github.com/satijalab/seurat/files/4071175/test_leiden.R.txt)

**Comment by andrewwbutler** [comment]
@TomKellyGenetics , it looks like the `leiden` method for sparse matrices ([here](https://github.com/TomKellyGenetics/leiden/blob/0aa310d471a8335582fce6958438b45c82ba80b1/R/leiden.R#L168-L202))  is converting `object` to an `igraph` object via `graph_from_adjacency_matrix`.  This explains why tests 1 and 3 above give identical results.  I'm fine with just always converting to a dense matrix on the Seurat side of things but just thought I'd point it out since that seems to be different than what you're expecting. I think you were probably trying to handle the sparse matrix case [here](https://github.com/TomKellyGenetics/leiden/blob/0aa310d471a8335582fce6958438b45c82ba80b1/R/leiden.R#L96-L123) but if a sparse matrix is passed, it will never hit that code chunk as it's not of the `matrix` class.

**Comment by vtraag** [comment]
For what it's worth, I hope to find some time in February to implement the Leiden algorithm directly in the both the R and Python interfaces of `igraph`. I already included the functionality in the C core of `igraph` (see https://github.com/igraph/igraph/pull/1259), which should be released shortly. That should address all shortcomings mentioned here, and should also be substantially faster.

**Comment by chlee-tabin** [comment]
@TomKellyGenetics Thank you so much!

> Please accept the PR to merge changes ([chlee-tabin@53f0ea8](https://github.com/chlee-tabin/seurat/commit/53f0ea8341092536b09ce222d4e197039e038bb8)) to the refactored version, this enables passing weighted igraph objects from `Seurat`.

I am very new of submitting PRs, so hope I did it correctly (I just merged the pull request you sent to the fork). BTW, I really like `leiden`, will continue using it and telling others!

**Comment by TomKellyGenetics** [comment]
Thanks @chlee-tabin that will add my changes to your PR here. I've merged updates from the `develop` branch of `Seurat` as well.

@andrewwbutler I think you're right. I must have changed handling of sparse matrices to use the igraph method as it performed better (for unweighted matrices). That would explain with the issues with `leiden.igraph` affected the `method = "matrix"` call as well. igraph objects, sparse, and dense matrices now support weights and return the same results in the updated R `leiden` package (as do the `Seurat` calls). I'll try to get a minor release on CRAN soon, just some package issues to fix with updated `roxygen2`, I think.

Once Leiden is supported by R-igraph, I'd recommend migrating to that.

**Comment by TomKellyGenetics** [comment]
The `leiden` R package version 0.3.2 is up on CRAN so the development version of Seurat can call it as a dependency. The issue seems to be a bug with `leiden` passing weights and Seurat `FindClusters` passes weighted sparse matrices to the igraph method. I'd suggest adding an argument to `FindClusters` to control whether weights are used or not. However, as this issue seems to affect many people, I'm okay to merge this PR and decide how to handle weights as a separate issue.

**Comment by andrewwbutler** [comment]
Ok, thanks @TomKellyGenetics . Merged this PR so the `matrix` option should now be working again

**Comment by TomKellyGenetics** [comment]
@andrewwbutler @chlee-tabin Thanks! Sorry for introducing the bug to Seurat 3.1.2 in the first place. Hopefully the igraph method handles weighted objects properly now too. Is it worth adding `weighted` flag to `FindClusters` to control this or should we leave it? If so I can submit a new PR / Issue. I think now it default to deriving weights from the integer values  of the adjacency matrix (Seurat `Graph` class).

**Comment by chlee-tabin** [comment]
> ```r
> adj.graph.weighted <- leiden(
>   object = igraph::graph_from_adjacency_matrix(input, weighted = TRUE),
>   seed = 42,
>   n_iterations = 10
> )
> head(table(adj.graph.weighted), 10)
> ```

@TomKellyGenetics 

I just want to comment on this now closed thread that after all the updates I did, there is still discrepancy between Test 3 and the other Test 1, 2, 4.

I just came to this due to my situation no longer allowing casting the matrix (which is too big), and wanted to try out method="igraph". It does not have weighted option, so it produces singleton issues with the method="igraph".

```
> pbmc_small %>% FindClusters( method = "matrix", algorithm = 4 ) %>% DimPlot()
Warning: Adding a command log without an assay associated with it
> pbmc_small %>% FindClusters( method = "igraph", algorithm = 4 ) %>% DimPlot()
58 singletons identified. 8 final clusters.
Warning: Adding a command log without an assay associated with it
```

**Comment by chlee-tabin** [comment]
I just want to mention that without `weights = TRUE`, the leiden algorithm of `FindCluster` still does not output the same partitions.

```
library(tidyverse)
library(Seurat)

pbmc_small %>% FindClusters( algorithm = 4, method = "matrix" ) %>% DimPlot()
pbmc_small %>% FindClusters( algorithm = 4, method = "igraph", weights = T ) %>% DimPlot()

# This is different and produces singletons than above
pbmc_small %>% FindClusters( algorithm = 4, method = "igraph" ) %>% DimPlot()
```

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Seurat_3.1.4    forcats_0.5.0   stringr_1.4.0   dplyr_0.8.5     purrr_0.3.3     readr_1.3.1    
 [7] tidyr_1.0.2     tibble_2.1.3    ggplot2_3.3.0   tidyverse_1.3.0

loaded via a namespace (and not attached):
  [1] TH.data_1.0-10      Rtsne_0.15          colorspace_1.4-1    ggridges_0.5.2      fs_1.3.2           
  [6] rstudioapi_0.11     farver_2.0.3        leiden_0.3.3        listenv_0.8.0       npsurv_0.4-0       
 [11] ggrepel_0.8.2       fansi_0.4.1         mvtnorm_1.1-0       lubridate_1.7.4     xml2_1.2.5         
 [16] codetools_0.2-16    splines_3.6.3       mnormt_1.5-6        lsei_1.2-0          TFisher_0.2.0      
 [21] jsonlite_1.6.1      broom_0.5.5         ica_1.0-2           cluster_2.1.0       dbplyr_1.4.2       
 [26] png_0.1-7           uwot_0.1.5          sctransform_0.2.1   compiler_3.6.3      httr_1.4.1         
 [31] backports_1.1.5     lazyeval_0.2.2      assertthat_0.2.1    Matrix_1.2-18       cli_2.0.2          
 [36] htmltools_0.4.0     tools_3.6.3         rsvd_1.0.3          igraph_1.2.4.2      gtable_0.3.0       
 [41] glue_1.3.2          reshape2_1.4.3      RANN_2.6.1          Rcpp_1.0.3          Biobase_2.46.0     
 [46] cellranger_1.1.0    vctrs_0.2.4         multtest_2.42.0     gdata_2.18.0        ape_5.3            
 [51] nlme_3.1-145        gbRd_0.4-11         lmtest_0.9-37       globals_0.12.5      rvest_0.3.5        
 [56] lifecycle_0.2.0     irlba_2.3.3         gtools_3.8.1        future_1.16.0       MASS_7.3-51.5      
 [61] zoo_1.8-7           scales_1.1.0        hms_0.5.3           parallel_3.6.3      sandwich_2.5-1     
 [66] RColorBrewer_1.1-2  gridExtra_2.3       reticulate_1.14     pbapply_1.4-2       stringi_1.4.6      
 [71] mutoss_0.1-12       plotrix_3.7-7       caTools_1.18.0      BiocGenerics_0.32.0 bibtex_0.4.2.2     
 [76] Rdpack_0.11-1       rlang_0.4.5         pkgconfig_2.0.3     bitops_1.0-6        lattice_0.20-40    
 [81] ROCR_1.0-7          labeling_0.3        htmlwidgets_1.5.1   patchwork_1.0.0     cowplot_1.0.0      
 [86] tidyselect_1.0.0    RcppAnnoy_0.0.16    plyr_1.8.6          magrittr_1.5        R6_2.4.1           
 [91] gplots_3.0.3        generics_0.0.2      multcomp_1.4-12     DBI_1.1.0           pillar_1.4.3       
 [96] haven_2.2.0         withr_2.1.2         sn_1.5-5            fitdistrplus_1.0-14 survival_3.1-11    
[101] tsne_0.1-3          future.apply_1.4.0  modelr_0.1.6        crayon_1.3.4        KernSmooth_2.23-16 
[106] plotly_4.9.2        grid_3.6.3          readxl_1.3.1        data.table_1.12.8   metap_1.3          
[111] reprex_0.3.0        digest_0.6.25       numDeriv_2016.8-1.1 RcppParallel_5.0.0  stats4_3.6.3       
[116] munsell_0.5.0       viridisLite_0.3.0  
```

Since the `weights` default is NULL, it was quite confusing for me to switch to the `method="igraph"`.

**Comment by TomKellyGenetics** [comment]
I've opened a new Issue to discuss weights in `FindClusters` and the default behaviour specifically. Weights are not automatically derived from igraph objects by `leiden::leiden`. Therefore it will differ from a matrix input if it is unweighted. We can derive weights from adjacency matrices as shown in the `leiden` package vignettes (although Seurat doesn't use this yet).

Please note that `weights = TRUE` is not the input that `FindClusters` expects. It needs to be an integer vector for each edge. Sorry the documentation (for the leiden package as well) should be updated to give further details on recent changes to handling of weights.

See this issue for further discussion: https://github.com/satijalab/seurat/issues/2574

I will test how weights are handled in the latest version of Seurat and R and get back to this.

**Comment by chlee-tabin** [comment]
```
> suppressMessages(library(SeuratData))
> library(leiden)
> 
> data("pbmc3k.final")
> input <- pbmc3k.final[["RNA_snn"]]
> 
> # Test 1
> sparse.input <- leiden(
+   object = input, 
+   seed = 42, 
+   n_iterations = 10
+ )
> head(table(sparse.input), 10)
sparse.input
  1   2   3   4   5   6   7   8   9  10 
570 492 344 272 255 225 162 145 127  32 
> 
> # Test 2
> dense.input <- leiden(
+   object = as.matrix(input), 
+   seed = 42, 
+   n_iterations = 10
+ )
> head(table(dense.input), 10)
dense.input
  1   2   3   4   5   6   7   8   9  10 
570 492 344 272 255 225 162 145 127  32 
> 
> # Test 3
> adj.graph <- leiden(
+   object = igraph::graph_from_adjacency_matrix(input),
+   seed = 42,
+   n_iterations = 10
+ )
> head(table(adj.graph), 10)
adj.graph
 1  2  3  4  5  6  7  8  9 10 
 4  2  2  2  1  1  1  1  1  1 
> all.equal(sparse.input, adj.graph)
[1] "Mean relative difference: 338.3939"
> #> [1] TRUE
> 
> # Test 4
> adj.graph.weighted <- leiden(
+   object = igraph::graph_from_adjacency_matrix(input, weighted = TRUE),
+   seed = 42,
+   n_iterations = 10
+ )
> head(table(adj.graph.weighted), 10)
adj.graph.weighted
  1   2   3   4   5   6   7   8   9  10 
570 492 344 272 255 225 162 145 127  32 
> all.equal(adj.graph.weighted, dense.input)
[1] TRUE
> #> [1] "Mean relative difference: 0.3211488"
> 
```

I just retried what @andrewwbutler did above, and as it shows, Test 1, 2, 4 all now give same results, but Test 3 still gives singletons. Test 3 is when the `weighted=TRUE` is removed, so naturally I tried to find whether the `weighted=TRUE` could be set from `FindClusters`.

At least from the `RunLeiden` code snippet in the github, it says

https://github.com/satijalab/seurat/blob/94343c4fdb35a3a1e7a7e14d4a0bb0cec657075c/R/clustering.R#L728-L733

if weights are NULL, then don't set that parameter to TRUE, and if weights are not NULL then just set the weighted = TRUE.

I have also tested with the small example as I presented above with `pbmc_small`, the partitions that the two setups are generating are exactly the same, whereas the `method=igraph` option with `weights=NULL` default produces a lot of singletons.

So whatever the intended weights parameters is for the `leiden` package, at least the `FindClusters` in `Seurat` only has a simple flow whether or not to have the `igraph::graph_from_adjacency_matrix` having the parameter `weighted=TRUE` or not before running `leiden::leiden`. That is what I understood so far.

So I am not sure what you intended with the `weights` parameter for `FindClusters`.

**Pull request merged**
