### PR TITLE
Update seurat.R

### PR DESCRIPTION
**Pull request by mashranga**
I think ggplot 2 has some automated bandwidth smoothing and it need to be controlled. Otherwise the violinplot is not possible to explain !!

### CODE REVIEW

**Comment by mschilli87** [comment]
If you already switch from automatic determination of the 'best' bandwidth to a fixed one, why not make it a user contrallable parameter (defaulting to `0.5` like you suggest)?

**Comment by mashranga** [comment]
This correction is in plot.Vln function which is not exported  and plot.Vln is called by VlnPlot function . But in VlnPlot function , there is no parameter to give that value !!

**Comment by mashranga** [comment]
I have asked for some explanation to R-help list !! 
here is the post link: 
https://stat.ethz.ch/pipermail/r-help/2017-July/448297.html

**Comment by mschilli87** [comment]
So again: If you switch from the self-adjusting solution to the fixed one (I'm all with you by the way), why not add this as a parameter (in `VlnPlot` with default `0.5`, passed down to `plot.Vln`, which wouldn't even need any default)?

**Comment by mashranga** [comment]
Thanks for your advice . I have already add this solution (fixed-adjusting bw = 0.5) to my analysis ..but I wondered about that self- adjusting solution.  Will this self-adjusting solution is always appropriate ? Or I am making any confusion on my understanding !!   

You can have a look into this .
https://stat.ethz.ch/pipermail/r-help/2017-July/448297.html

**Pull request closed without merging**
