### PR TITLE
Use more secure HTTPS URL in `README.md`

### PR DESCRIPTION
**Pull request by paulmenzel**

### CODE REVIEW

**Comment by mschilli87** [comment]
I'm getting a certificate error on https://www.satijalab.org/seurat. :disappointed:

**Comment by paulmenzel** [comment]
Dear Marcel,

On 08/20/18 12:48, Marcel Schilling wrote:
> I'm getting a certificate error on https://www.satijalab.org/seurat.
> :disappointed:

I noticed this error too, and updated the commit.

**Comment by mschilli87** [comment]
I still see https://www.satijalab.org/seurat instead of https://satijalab.org/seurat/ in the commit in this PR. Did you push after adding a commit or force push after amending the first one?

**Comment by paulmenzel** [comment]
On 08/20/18 17:50, Marcel Schilling wrote:
> I still see https://www.satijalab.org/seurat instead of
> https://satijalab.org/seurat/ in the commit in this PR. Did you push
> after adding a commit or force push after amending the first one?
I forgot to commit this change locally, and only updated the commit
message. Sorry. It should be fixed now.

**Comment by andrewwbutler** [comment]
Thanks Paul!

**Pull request merged**
